# Generated by Django 4.1.5 on 2023-01-19 18:29

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[core.validators.validate_birth_date]),
        ),
    ]
